---
title: "GGPlot Snippets"
description: "This is a collection of plots I find myself making often."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GGplot: Common plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval = TRUE)
library(tidyverse)
```

This is a collection of plots I find myself making often. 


### Specify colors

By overall: 
```{r}
data(CO2)
CO2 %>% ggplot(aes(conc,uptake,col=Treatment)) + geom_point() +
  scale_color_manual(values = c("red","green"))
```

Categories in order unless specified: 
```{r}
data(CO2)
CO2 %>% ggplot(aes(conc,uptake,col=Treatment)) + geom_point() +
  scale_color_manual(values = c("chilled"="red","nonchilled"="green"))
```

GGplot default:
```{r}
CO2 %>% ggplot(aes(conc,uptake,col=Treatment)) + geom_point() +
  scale_color_manual(values = c("#F8766D","#00BFC4"))
```

Brewer palette
```{r}
CO2 %>% ggplot(aes(conc,uptake,col=Treatment)) + geom_point() +
  scale_color_brewer(palette = "Dark2")
```

Type of scale: seq, div, qual
```{r}
CO2 %>% ggplot(aes(conc,uptake,col=Treatment)) + geom_point() +
  scale_color_brewer(type="seq",direction = 1) 
```

Greadient:
```{r}
CO2 %>% ggplot(aes(conc,uptake,col=conc)) + geom_point() +
  scale_color_gradient(low="blue", high="red")
```

Keep levels even if not in subset plotted
```{r}
CO2 %>% filter(Treatment == "chilled") %>%
  ggplot(aes(conc,uptake,col=Treatment)) + geom_point() +
  scale_color_manual(values = c("#F8766D","#00BFC4"),drop  = FALSE)
```

More info at http://www.sthda.com/english/wiki/ggplot2-colors-how-to-change-colors-automatically-and-manually


### Scatter plot 

```{r}
data(CO2)
CO2 %>% 
  ggplot(aes(conc,uptake)) +
  geom_point()
```


### Plot of regression coefficients
```{r}
library(coefplot)
data("mtcars")
m1 = glm(am == 1 ~ mpg + cyl + disp  + wt, data = mtcars, family = "binomial") %>% 
  coefplot() %>% 
  print()
```